// <auto-generated />
using System;
using DataAccess.Concrete.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220921133616_skyapp")]
    partial class skyapp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Entities.Concrete.Order", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ColorOrInch")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PackageType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WashType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("k28")
                        .HasColumnType("int");

                    b.Property<int>("k30")
                        .HasColumnType("int");

                    b.Property<int>("k32")
                        .HasColumnType("int");

                    b.Property<int>("k34")
                        .HasColumnType("int");

                    b.Property<int>("k36")
                        .HasColumnType("int");

                    b.Property<int>("k38")
                        .HasColumnType("int");

                    b.Property<int>("k40")
                        .HasColumnType("int");

                    b.Property<int>("k42")
                        .HasColumnType("int");

                    b.Property<int>("k44")
                        .HasColumnType("int");

                    b.Property<int>("k46")
                        .HasColumnType("int");

                    b.Property<int>("k48")
                        .HasColumnType("int");

                    b.Property<int>("k50")
                        .HasColumnType("int");

                    b.Property<int?>("kCount")
                        .HasColumnType("int");

                    b.Property<int>("s28")
                        .HasColumnType("int");

                    b.Property<int>("s30")
                        .HasColumnType("int");

                    b.Property<int>("s32")
                        .HasColumnType("int");

                    b.Property<int>("s34")
                        .HasColumnType("int");

                    b.Property<int>("s36")
                        .HasColumnType("int");

                    b.Property<int>("s38")
                        .HasColumnType("int");

                    b.Property<int>("s40")
                        .HasColumnType("int");

                    b.Property<int>("s42")
                        .HasColumnType("int");

                    b.Property<int>("s44")
                        .HasColumnType("int");

                    b.Property<int>("s46")
                        .HasColumnType("int");

                    b.Property<int>("s48")
                        .HasColumnType("int");

                    b.Property<int>("s50")
                        .HasColumnType("int");

                    b.Property<int?>("sCount")
                        .HasColumnType("int");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("orders");
                });
#pragma warning restore 612, 618
        }
    }
}
